#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 使用新版驱动类
    username: root
    password: mysqlmima123
    url: jdbc:mysql://localhost:3306/b_myproject?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

#配置mybatis实体和xml映射
mybatis:
  #映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true